name = "matjib-ai"
main = "worker.js"
compatibility_date = "2023-10-30"

[vars]
# OPENAI_API_KEY = "your-openai-api-key-here" # It is recommended to use `wrangler secret put OPENAI_API_KEY` instead of plain text.
